Repository uju-in/lime-frontend, pull requests merged in 2024-02, with the labels that each got.

#16 design: 투표 생성 페이지 UI
  .eslintrc.json
  public/image/icon/icon-circle_minus.svg
  public/image/icon/icon-circle_plus.svg
  public/image/icon/icon-plus.svg
  src/app/(route)/votes/add-vote/_component/VoteForm.tsx
  src/app/(route)/votes/add-vote/_component/VoteModal.tsx
  src/app/(route)/votes/add-vote/layout.tsx
  src/app/(route)/votes/add-vote/page.tsx
  src/app/(route)/votes/page.tsx
  src/app/_components/modal/index.tsx
Labels: design

#17 refactor: 토큰 저장 방식 변경(localStorage -> cookie)
  src/app/_components/GetSearchParams.tsx
  src/app/_utils/cookie.ts
Labels: enhancement

#21 design: 투표 상세 페이지 UI 구현
  public/image/icon/icon-arrow_long_right.svg
  src/app/(route)/votes/[voteId]/layout.tsx
  src/app/(route)/votes/[voteId]/page.tsx
Labels: design

#23 design: 투표 메인 페이지 UI
  src/app/(route)/votes/[voteId]/layout.tsx
  src/app/(route)/votes/add-vote/layout.tsx
  src/app/(route)/votes/layout.tsx
  src/app/(route)/votes/page.tsx
Labels: design

#24 refactor: clsx, tailwind-merge 도입
  package.json
  src/app/(route)/items/[itemID]/_component/Review.tsx
  src/app/(route)/items/[itemID]/_component/ReviewSection.tsx
  src/app/(route)/items/_components/SideMenu.tsx
  src/app/(route)/items/_components/SortBox.tsx
  src/app/(route)/join/_components/CareerSelector.tsx
  src/app/(route)/saves/[folderName]/_component/SaveFolderHeader.tsx
  src/app/(route)/saves/_component/AddFolderModal.tsx
  src/app/(route)/saves/_component/SaveFolderGroupItem.tsx
  src/app/_components/categorySelector/index.tsx
  src/app/_components/modal/index.tsx
  src/app/_utils/twMerge.ts
  yarn.lock
Labels: enhancement

#22 feat: 투표 상세 페이지 API 연동
  src/app/(route)/items/[itemID]/_component/Review.tsx
  src/app/(route)/items/[itemID]/page.tsx
  src/app/(route)/votes/[voteId]/_component/DetailViewButton.tsx
  src/app/(route)/votes/[voteId]/_component/ManagementButton.tsx
  src/app/(route)/votes/[voteId]/_component/ProgressBar.tsx
  src/app/(route)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/votes/[voteId]/_component/VoteItem.tsx
  src/app/(route)/votes/[voteId]/page.tsx
  src/app/(route)/votes/_utils/truncateString.ts
  src/app/_hook/api/useDeleteVote.ts
  src/app/_hook/api/useParticipationVote.ts
  src/app/_hook/api/useReParticipation.ts
  src/app/_hook/api/useVoteDetail.ts
  src/app/_types/detailVote.type.ts
  src/app/_utils/categoryFormatter.ts
  src/app/_utils/dateFormatter.ts
Labels: feature

#26 refactor: 아이템 & 리뷰 API 변경 사항 적용
  src/app/(route)/items/[itemID]/_component/EditButtons.tsx
  src/app/(route)/items/[itemID]/_component/Review.tsx
  src/app/(route)/items/[itemID]/_component/ReviewModal.tsx
  src/app/(route)/items/[itemID]/_component/ReviewSection.tsx
  src/app/(route)/items/[itemID]/page.tsx
  src/app/_components/modal/index.tsx
  src/app/_hook/api/useAddItem.ts
  src/app/_hook/api/useAddReview.ts
  src/app/_hook/api/useDeleteReview.ts
  src/app/_hook/api/useEditReview.ts
  src/app/_hook/api/useReviewLikeAction.ts
  src/app/_hook/api/useSaveToWishlist.ts
  src/app/_hook/api/useSearchItemQuery.ts
  src/app/_types/review.type.ts
Labels: enhancement

#29 feat: query key factory 구조 적용
  .eslintrc.json
  package.json
  src/app/(route)/items/[itemID]/_component/ActionButtons.tsx
  src/app/(route)/items/[itemID]/_component/EditButtons.tsx
  src/app/(route)/items/[itemID]/_component/Review.tsx
  src/app/(route)/items/[itemID]/_component/ReviewModal.tsx
  src/app/(route)/items/[itemID]/_component/ReviewSection.tsx
  src/app/(route)/items/[itemID]/page.tsx
  src/app/(route)/items/_components/ItemList.tsx
  src/app/(route)/items/add-item/_component/PostForm.tsx
  src/app/(route)/join/_components/UserInfoField.tsx
  src/app/(route)/votes/[voteId]/_component/ManagementButton.tsx
  src/app/(route)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/votes/[voteId]/page.tsx
  src/app/_hook/api/auth/useNicknameValidation.ts
  src/app/_hook/api/auth/useSignUp.ts
  src/app/_hook/api/index.ts
  src/app/_hook/api/items/index.ts
  src/app/_hook/api/items/useAddItem.ts
  src/app/_hook/api/items/useItemDetail.ts
  src/app/_hook/api/items/useItemListData.ts
  src/app/_hook/api/items/useSaveToWishlist.ts
  src/app/_hook/api/reviews/index.ts
  src/app/_hook/api/reviews/useAddReview.ts
  src/app/_hook/api/reviews/useDeleteReview.ts
  src/app/_hook/api/reviews/useEditReview.ts
  src/app/_hook/api/reviews/useReviewLikeAction.ts
  src/app/_hook/api/reviews/useReviewListData.ts
  src/app/_hook/api/useGetItemDetail.ts
  src/app/_hook/api/votes/index.ts
  src/app/_hook/api/votes/useDeleteVote.ts
  src/app/_hook/api/votes/useParticipationVote.ts
  src/app/_hook/api/votes/useReParticipation.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  yarn.lock
Labels: feature

#27 feat: 투표 리스트 API 연동
  public/image/icon/icon-arrow_top.svg
  src/app/(route)/votes/[voteId]/_component/ProgressBar.tsx
  src/app/(route)/votes/[voteId]/page.tsx
  src/app/(route)/votes/_component/MenuButtons.tsx
  src/app/(route)/votes/_component/RankingList.tsx
  src/app/(route)/votes/_component/SortButtons.tsx
  src/app/(route)/votes/_component/VoteList.tsx
  src/app/(route)/votes/_constants/index.ts
  src/app/(route)/votes/_utils/defaultCategory.ts
  src/app/(route)/votes/page.tsx
  src/app/_components/layout/Header.tsx
  src/app/_hook/api/votes/index.ts
  src/app/_hook/api/votes/useVoteListData.ts
  src/app/_hook/api/votes/useVoteRanking.ts
  src/app/_types/vote.type.ts
  src/app/_utils/categoryFormatter.ts
Labels: feature

#30 feat: 투표 생성 페이지 API 연동
  next.config.js
  src/app/(route)/votes/add-vote/_component/FavoriteItem.tsx
  src/app/(route)/votes/add-vote/_component/FavoriteItemList.tsx
  src/app/(route)/votes/add-vote/_component/Folder.tsx
  src/app/(route)/votes/add-vote/_component/FolderList.tsx
  src/app/(route)/votes/add-vote/_component/ItemSelector.tsx
  src/app/(route)/votes/add-vote/_component/VoteForm.tsx
  src/app/(route)/votes/add-vote/_component/VoteItemList.tsx
  src/app/(route)/votes/add-vote/_component/VoteModal.tsx
  src/app/(route)/votes/add-vote/_utils/truncateString.ts
  src/app/_hook/api/votes/index.ts
  src/app/_hook/api/votes/useAddVote.ts
  src/app/_hook/api/votes/useFavoritesList.ts
  src/app/_types/addVote.type.ts
  src/app/_types/saveItem.type.ts
Labels: feature

#31 feat: toast UI 추가
  package.json
  src/app/_components/layout/Layout.tsx
  src/app/_utils/toast.ts
  yarn.lock
Labels: feature

#32 feat: 찜 목록 API 연동
  src/app/(route)/items/_components/SideMenu.tsx
  src/app/(route)/saves/[folderId]/_component/SaveFolderComponent.tsx
  src/app/(route)/saves/[folderId]/_component/SaveFolderHeader.tsx
  src/app/(route)/saves/[folderId]/_component/SaveItem.tsx
  src/app/(route)/saves/[folderId]/_component/SaveItemList.tsx
  src/app/(route)/saves/[folderId]/_component/index.ts
  src/app/(route)/saves/[folderId]/page.tsx
  src/app/(route)/saves/[folderName]/_component/SaveItemList.tsx
  src/app/(route)/saves/[folderName]/page.tsx
  src/app/(route)/saves/_component/AddFolderModal.tsx
  src/app/(route)/saves/_component/MoveFolderModal.tsx
  src/app/(route)/saves/_component/SaveComponent.tsx
  src/app/(route)/saves/_component/SaveFolderGroupItem.tsx
  src/app/(route)/saves/_component/SaveHeader.tsx
  src/app/(route)/saves/_component/SaveList.tsx
  src/app/(route)/saves/page.tsx
  src/app/_hook/api/saves/index.ts
  src/app/_hook/api/saves/useAddSaveFolder.ts
  src/app/_hook/api/saves/useChangeSaveFolderName.ts
  src/app/_hook/api/saves/useDeleteSave.ts
  src/app/_hook/api/saves/useMoveSaveItems.ts
  src/app/_hook/api/saves/useSavesList.ts
  src/app/_types/save.type.ts
Labels: feature
