Repository uju-in/lime-frontend, pull requests merged in 2024-04, with the labels that each got.

#50 feat: next client cookies 라이브러리 적용
  package.json
  src/app/(route)/(withLayout)/layout.tsx
  src/app/_hook/api/reviews/useReviewListData.ts
  src/app/_hook/api/saves/useSavesList.ts
  src/app/_hook/api/votes/useFavoritesList.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  yarn.lock
Labels: feature

#52 feat: middleware 추가
  src/app/_components/layout/Header.tsx
  src/app/_hook/api/auth/useTokenValidity.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  src/middleware.ts
Labels: feature

#51 fix: 찜 목록 QA 수정
  src/app/(route)/(withLayout)/saves/[folderId]/_component/SaveFolderHeader.tsx
  src/app/(route)/(withLayout)/saves/_component/AddFolderModal.tsx
  src/app/(route)/(withLayout)/saves/_component/MoChangeFolderNameModal.tsx
  src/app/(route)/(withLayout)/saves/_component/MoveFolderModal.tsx
  src/app/(route)/(withLayout)/saves/_component/SaveComponent.tsx
  src/app/(route)/(withLayout)/saves/_utils/validation.ts
Labels: bug, feature

#54 feat: 권한별 페이지 리다이렉트 처리 구현
  src/app/_constants/error.ts
  src/app/_hook/api/auth/useTokenValidity.ts
  src/app/_hook/api/items/useAddItem.ts
  src/app/_hook/api/items/useItemListData.ts
  src/app/_hook/api/items/useSaveToWishlist.ts
  src/app/_hook/api/reviews/useAddReview.ts
  src/app/_hook/api/reviews/useDeleteReview.ts
  src/app/_hook/api/reviews/useEditReview.ts
  src/app/_hook/api/reviews/useReviewLikeAction.ts
  src/app/_hook/api/reviews/useReviewListData.ts
  src/app/_hook/api/saves/useAddSaveFolder.ts
  src/app/_hook/api/saves/useChangeSaveFolderName.ts
  src/app/_hook/api/saves/useDeleteSave.ts
  src/app/_hook/api/saves/useMoveSaveItems.ts
  src/app/_hook/api/votes/useAddVote.ts
  src/app/_hook/api/votes/useDeleteVote.ts
  src/app/_hook/api/votes/useFavoritesList.ts
  src/app/_hook/api/votes/useParticipationVote.ts
  src/app/_hook/api/votes/useReParticipation.ts
  src/app/_hook/common/useHandleApiError.ts
  src/middleware.ts
Labels: feature

#55 refactor: 투표 영역 성능 최적화
  src/app/(route)/(withLayout)/_components/VoteSection.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSection.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSkeletonUI.tsx
  src/app/(route)/(withLayout)/items/_components/Item.tsx
  src/app/(route)/(withLayout)/layout.tsx
  src/app/(route)/(withLayout)/page.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/FavoritesVoteItem.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/ManagementButton.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteDetail.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_utils/validation.ts
  src/app/(route)/(withLayout)/votes/[voteId]/layout.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/page.tsx
  src/app/(route)/(withLayout)/votes/_component/EmptyVoteList.tsx
  src/app/(route)/(withLayout)/votes/_component/RankingList.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteItem.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteItemSkeleton.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteList.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteForm.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteModal.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_utils/validation.ts
  src/app/(route)/(withLayout)/votes/add-vote/layout.tsx
  src/app/(route)/(withLayout)/votes/add-vote/page.tsx
  src/app/(route)/(withLayout)/votes/page.tsx
  src/app/(route)/(withoutLayout)/join/page.tsx
  src/app/_components/infiniteScrollTrigger/index.tsx
  src/app/_components/layout/mobile/MoHeader.tsx
  src/app/_constants/images.ts
  src/app/_hook/api/votes/useVoteDetail.ts
Labels: enhancement

#56 refactor: 아이템 상세 & 리뷰 컴포넌트 구조 변경 및 최적화 작업
  src/app/(route)/(withLayout)/items/[itemId]/_component/ActionButtons.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ItemDetail.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ItemDetailView.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewModal.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewModalForm.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewModalHeader.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewModalItemDisplay.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSection.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSortOptions.tsx
  src/app/(route)/(withLayout)/items/[itemId]/page.tsx
  src/app/_components/confirm/index.tsx
  src/app/_hook/api/items/useItemDetail.ts
  src/app/_types/item.type.ts
  src/app/_types/review.type.ts
Labels: enhancement

#57 feat: 로그인 버튼 추가
  src/app/(route)/(withLayout)/layout.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/search/SearchButton.tsx
  src/app/_components/layout/search/SearchHeader.tsx
Labels: feature

#58 feat: React ErrorBoundary 적용
  .eslintrc.json
  src/app/(route)/(withLayout)/items/[itemId]/_component/ItemDetailPage.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ItemDetailView.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewHeader.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSection.tsx
  src/app/(route)/(withLayout)/items/[itemId]/page.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteDetail.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteDetailPage.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/_component/VoteItemInfo.tsx
  src/app/(route)/(withLayout)/votes/[voteId]/page.tsx
  src/app/(route)/(withLayout)/votes/_component/RankingList.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteListPage.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/AddVotePage.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/FavoriteItemList.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/MoItemSelectHeader.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteForm.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteItemsSelector.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteModal.tsx
  src/app/(route)/(withLayout)/votes/add-vote/_component/VoteModalHeader.tsx
  src/app/(route)/(withLayout)/votes/add-vote/page.tsx
  src/app/(route)/(withLayout)/votes/page.tsx
  src/app/_components/errorBoundary/index.tsx
  src/app/_components/errorFullback/index.tsx
  src/app/_components/loading/index.tsx
  src/app/_hook/api/items/useItemDetail.ts
  src/app/_hook/api/items/useSaveToWishlist.ts
  src/app/_hook/api/votes/useFavoritesList.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  src/app/_hook/api/votes/useVoteRanking.ts
  src/app/_types/addVote.type.ts
  src/app/not-found.tsx
Labels: feature
