Repository uju-in/lime-frontend, pull requests merged in 2024-03, with the labels that each got.

#34 refactor: 투표 도메인 수정 사항 반영
  public/image/icon/icon-plus_858585.svg
  src/app/(route)/votes/[voteId]/_component/ManagementButton.tsx
  src/app/(route)/votes/[voteId]/_component/ProgressBar.tsx
  src/app/(route)/votes/[voteId]/_component/VoteDetail.tsx
  src/app/(route)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/votes/[voteId]/_component/VoteItem.tsx
  src/app/(route)/votes/[voteId]/page.tsx
  src/app/(route)/votes/_component/CreateVoteButton.tsx
  src/app/(route)/votes/_component/MenuButtons.tsx
  src/app/(route)/votes/_component/RankingList.tsx
  src/app/(route)/votes/_component/VoteList.tsx
  src/app/(route)/votes/add-vote/_component/FavoriteItemList.tsx
  src/app/(route)/votes/add-vote/_component/ItemSelector.tsx
  src/app/(route)/votes/add-vote/_component/VoteForm.tsx
  src/app/(route)/votes/add-vote/_utils/truncateString.ts
  src/app/(route)/votes/page.tsx
  src/app/_components/categoryPicker/CategoryPicker.tsx
  src/app/_hook/api/votes/index.ts
  src/app/_hook/api/votes/useAddVote.ts
  src/app/_hook/api/votes/useDeleteVote.ts
  src/app/_hook/api/votes/useParticipationVote.ts
  src/app/_hook/api/votes/useReParticipation.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  src/app/_hook/api/votes/useVoteRanking.ts
  src/app/_utils/dateFormatter.ts
  src/app/_utils/defaultCategory.ts
Labels: enhancement

#35 design: 인덱스 페이지, Footer UI 구현
  public/image/icon/icon-arrow_long_right_white.svg
  public/image/icon/icon-facebook.svg
  public/image/icon/icon-instagram.svg
  public/image/icon/icon-mail.svg
  public/image/icon/icon-twitter.svg
  public/image/icon/icon-youtube.svg
  src/app/_components/GetSearchParams.tsx
  src/app/_components/layout/Footer.tsx
  src/app/page.tsx
Labels: design

#37 refactor: 아이템 상세 페이지 수정 사항 반영
  next.config.js
  package.json
  src/app/(route)/items/[itemId]/_component/ActionButtons.tsx
  src/app/(route)/items/[itemId]/_component/ItemDetailView.tsx
  src/app/(route)/items/[itemId]/_component/ReviewModal.tsx
  src/app/(route)/items/[itemId]/_component/ReviewSection.tsx
  src/app/(route)/items/[itemId]/_utils/validation.ts
  src/app/(route)/items/[itemId]/page.tsx
  src/app/(route)/votes/[voteId]/_component/VoteDetail.tsx
  src/app/(route)/votes/[voteId]/page.tsx
  src/app/_components/GetSearchParams.tsx
  src/app/_hook/api/items/index.ts
  src/app/_hook/api/items/useAddItem.ts
  src/app/_hook/api/items/useItemDetail.ts
  src/app/_hook/api/items/useSaveToWishlist.ts
  src/app/_hook/api/reviews/useAddReview.ts
  src/app/_hook/api/reviews/useDeleteReview.ts
  src/app/_hook/api/reviews/useEditReview.ts
  src/app/_hook/api/reviews/useReviewLikeAction.ts
  src/app/_hook/api/reviews/useReviewListData.ts
  src/app/_hook/api/votes/useAddVote.ts
  src/app/_hook/api/votes/useDeleteVote.ts
  src/app/_hook/api/votes/useFavoritesList.ts
  src/app/_hook/api/votes/useParticipationVote.ts
  src/app/_hook/api/votes/useReParticipation.ts
  src/app/_hook/api/votes/useVoteDetail.ts
  src/app/_types/review.type.ts
  src/app/_utils/cookie.ts
  yarn.lock
Labels: enhancement

#36 feat: 아이템 리스트 API 수정사항 반영 및 검색 UI 구현 / API 연동
  package.json
  src/app/(route)/items/_components/Item.tsx
  src/app/(route)/items/_components/ItemList.tsx
  src/app/(route)/search/_components/SearchItemList.tsx
  src/app/(route)/search/_components/SortBox.tsx
  src/app/(route)/search/_constants/index.ts
  src/app/(route)/search/page.tsx
  src/app/_atoms/searchViewState.ts
  src/app/_components/RecoilRootProvider.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/ItemSection.tsx
  src/app/_components/layout/Search.tsx
  src/app/_components/layout/search/RecentSearchKeywordItem.tsx
  src/app/_components/layout/search/RecentSearchKeywordList.tsx
  src/app/_components/layout/search/SearchItem.tsx
  src/app/_components/layout/search/SearchItemList.tsx
  src/app/_hook/api/items/index.ts
  src/app/_hook/api/items/useItemListData.ts
  src/app/_hook/api/items/useSearchItem.ts
  src/app/_types/searchItem.type.ts
  src/app/_utils/localStorage.ts
  src/app/layout.tsx
  yarn.lock
Labels: feature, design

#38 feat: 메인 페이지 API 연동
  src/app/(route)/_components/ItemSection.tsx
  src/app/(route)/_components/LoadMoreButton.tsx
  src/app/(route)/_components/VoteSection.tsx
  src/app/(route)/_utils/getSectionPath.ts
  src/app/(route)/items/_components/Item.tsx
  src/app/(route)/votes/[voteId]/_component/FavoritesVoteItem.tsx
  src/app/(route)/votes/[voteId]/_component/VoteInfo.tsx
  src/app/(route)/votes/_component/VoteItem.tsx
  src/app/(route)/votes/_component/VoteList.tsx
  src/app/_hook/api/home/useGetItems.ts
  src/app/_hook/api/home/useGetVotes.ts
  src/app/_hook/api/items/useSaveToWishlist.ts
  src/app/_hook/api/votes/useVoteListData.ts
  src/app/_types/home.type.ts
  src/app/_types/item.type.ts
  src/app/page.tsx
Labels: feature

#39 design: 로그인, 프로필 작성 페이지 반응형 구현
  public/image/icon/icon-arrow_left_black.svg
  src/app/(route)/join/_components/CareerSelector.tsx
  src/app/(route)/join/_components/JoinHeader.tsx
  src/app/(route)/join/_components/MbtiSelector.tsx
  src/app/(route)/join/_components/UserInfoField.tsx
  src/app/(route)/join/page.tsx
  src/app/(route)/login/page.tsx
  src/app/_components/categorySelector/index.tsx
  src/app/_components/layout/mobile/MoHeader.tsx
  tailwind.config.ts
Labels: design

#41 refactor: 카카오 로그인 accessToken 저장 로직 변경
  src/app/(route)/(withLayout)/page.tsx
  src/app/(route)/(withoutLayout)/login/_components/KakaoLoginButton.tsx
  src/app/(route)/(withoutLayout)/oauth-redirect/_components/RedirectComponent.tsx
  src/app/(route)/(withoutLayout)/oauth-redirect/page.tsx
  src/app/_components/GetSearchParams.tsx
  src/app/_hook/api/auth/useRequestToken.ts
Labels: enhancement

#43 design: 마이페이지 와이어프레임 구현
  public/image/icon/icon-bucket.svg
  public/image/icon/icon-feed.svg
  public/image/icon/icon-inventory.svg
  public/image/icon/icon-pencil_white.svg
  public/image/icon/icon-vote.svg
  src/app/(route)/(withLayout)/mypage/layout.tsx
  src/app/(route)/(withLayout)/mypage/page.tsx
Labels: design

#42 design: 아이템 생성 및 검색 반응형 적용
  public/image/icon/icon-back.svg
  public/image/icon/icon-close_white.svg
  public/image/icon/icon-search_dfdfdf.svg
  src/app/(route)/(withLayout)/items/add-item/_component/PostForm.tsx
  src/app/(route)/(withLayout)/items/add-item/layout.tsx
  src/app/(route)/(withLayout)/items/add-item/page.tsx
  src/app/(route)/(withoutLayout)/mo-search/_components/RecentSearchItem.tsx
  src/app/(route)/(withoutLayout)/mo-search/_components/RecentSearchList.tsx
  src/app/(route)/(withoutLayout)/mo-search/_components/SearchComponent.tsx
  src/app/(route)/(withoutLayout)/mo-search/page.tsx
  src/app/_components/layout/mobile/MoHeader.tsx
  src/app/_components/layout/search/SearchItem.tsx
  src/app/_components/layout/search/SearchItemList.tsx
  src/app/layout.tsx
Labels: design

#44 design: 홈페이지 반응형 구현
  public/image/icon/icon-arrow_right_A5A5A5.svg
  public/image/icon/icon-search_DFDFDF.svg
  public/image/icon/icon-search_black.svg
  src/app/(route)/(withLayout)/_components/ItemSection.tsx
  src/app/(route)/(withLayout)/_components/LoadMoreButton.tsx
  src/app/(route)/(withLayout)/_components/MoHomeHeader.tsx
  src/app/(route)/(withLayout)/_components/NoResults.tsx
  src/app/(route)/(withLayout)/_components/VoteSection.tsx
  src/app/(route)/(withLayout)/items/_components/Item.tsx
  src/app/(route)/(withLayout)/page.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteItem.tsx
  src/app/(route)/(withLayout)/votes/_component/VoteList.tsx
  src/app/(route)/_components/ItemSection.tsx
  src/app/(route)/_components/LoadMoreButton.tsx
  src/app/(route)/_components/VoteSection.tsx
  src/app/_hook/common/useScrollDirection.ts
  src/app/layout.tsx
Labels: design

#46 design: 아이템 리스트 반응형 구현
  public/image/icon/icon-more.svg
  public/image/icon/icon-plus_white_36.svg
  public/image/icon/icon-save_white.svg
  public/image/icon/icon-search_dfdfdf.svg
  src/app/(route)/(withLayout)/items/_components/FloatingButton.tsx
  src/app/(route)/(withLayout)/items/_components/Item.tsx
  src/app/(route)/(withLayout)/items/_components/ItemList.tsx
  src/app/(route)/(withLayout)/items/_components/SideMenu.tsx
  src/app/(route)/(withLayout)/items/add-item/layout.tsx
  src/app/(route)/(withLayout)/items/layout.tsx
  src/app/(route)/(withLayout)/items/page.tsx
  src/app/_components/categoryPicker/CategoryPicker.tsx
  src/app/_components/layout/Footer.tsx
  src/app/_components/layout/Header.tsx
  src/app/_hook/api/items/useItemListData.ts
  src/app/_hook/common/useScrollDirection.ts
Labels: design

#48 design: 아이템 상세 페이지 반응형 구현
  public/image/icon/icon-camera.svg
  src/app/(route)/(withLayout)/items/[itemId]/_component/ActionButtons.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/Breadcrumb.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/EditButtons.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ItemDetailView.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/MoItemDetailHeader.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/Review.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewImage.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewImagesDisplay.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewLikeButton.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewModal.tsx
  src/app/(route)/(withLayout)/items/[itemId]/_component/ReviewSection.tsx
  src/app/(route)/(withLayout)/items/[itemId]/page.tsx
  src/app/(route)/(withLayout)/items/_components/Item.tsx
  src/app/(route)/(withLayout)/items/_components/MoItemListHeader.tsx
  src/app/(route)/(withLayout)/items/add-item/_component/PostForm.tsx
  src/app/(route)/(withLayout)/items/add-item/layout.tsx
  src/app/(route)/(withLayout)/items/layout.tsx
  src/app/(route)/(withLayout)/items/page.tsx
  src/app/(route)/(withLayout)/items/review-images/_component/DetailImage.tsx
  src/app/(route)/(withLayout)/items/review-images/_component/MoImageDetailHeader.tsx
  src/app/(route)/(withLayout)/items/review-images/page.tsx
  src/app/_atoms/reviewImagesViewState.ts
  src/app/_components/categoryPicker/CategoryPicker.tsx
  src/app/_components/confirm/index.tsx
  src/app/_utils/localStorage.ts
Labels: design
